#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
quien=$(whoami)
donde=$(hostname)
nom=$(basename "$0")

function ayuda() {
	echo "Ejemplo: $nom /home/user/key"
	exit 1
}

if [[ "$EUID" = "0" ]]; then
	echo "ERROR: NO debe ser root."
	exit 1
fi

if [[ $(dpkg --get-selections | grep -w "haveged" | awk '{print $1}' | head -1) = haveged ]]; then
	echo "El paquete haveged esta instalado."
else
	echo "ERROR: El paquete haveged no esta instalado, se procede a instalar"
	apt update -q
	apt -y install haveged
	apt clean
fi

if [[ -z "$1" ]]; then
	ayuda
fi

rm -f $1
rm -f $1.pem
rm -f $1.pub

ssh-keygen -P "" -t rsa -b 4096 -C $quien@$donde -f $1
mv -f $1 $1.pem
clear

if [[ $XDG_SESSION_TYPE = x11 ]]; then
	if [[ $(dpkg --get-selections | grep -w "xclip" | awk '{print $1}' | head -1) = xclip ]]; then
		cat $1.pub | xclip -sel c
		cat $1.pub
		echo ""
		echo "Llave publica copiada al portapapeles."
	else
		cat $1.pub
	fi
else
	if [[ $(dpkg --get-selections | grep -w "wl-clipboard" | awk '{print $1}' | head -1) = wl-clipboard ]]; then
		cat $1.pub
		wl-copy -c
		wl-copy $(cat $1.pub)
		echo ""
		echo "Llave publica copiada al portapapeles."
	else
		cat $1.pub
	fi
fi

echo "Finalizado."
exit 0
